#!/bin/bash
. /usr/share/debconf/confmodule
db_version 2.0
db_capb backup

keys=( server database user pass path )
maxkeys=$((${#keys[@]} -1))

index=0
while [ "$index" -ge 0 -a "$index" -le $maxkeys ]; do
		  db_input high acspanel-client-ddns/${keys[$index]} || true
		  if db_go; then
			  index=$(($index + 1))
		  else
			  index=$(($index - 1))
		  fi
done

for key in ${keys[*]}; do
	db_get acspanel-client-ddns/$key
	value=$RET
	if [ "x$value" != "x" ]; then
		sed -i -e "s|^$key.*$|$key=$value|" /etc/acspanel/ddns-client/config
	fi
done
