#!/bin/bash
. /usr/share/debconf/confmodule
db_version 2.0
db_capb backup

FILES="libnss-mysql.cfg libnss-mysql-root.cfg"
ETC=/etc
ZETC=/etc/acspanel/users-mysql

keys=( host database username password )
maxkeys=$((${#keys[@]} -1))

index=0
while [ "$index" -ge 0 -a "$index" -le $maxkeys ]; do
                  db_input high acspanel-users-mysql/${keys[$index]} || true
                  if db_go; then
                          index=$(($index + 1))
                  else   
                          index=$(($index - 1))
                  fi
done

for key in ${keys[*]}; do
        db_get acspanel-users-mysql/$key
        value=$RET
        if [ "x$value" != "x" ]; then
		sed -i -e "s|^$key.*$|$key\t$value|" $ZETC/libnss-mysql.cfg
		sed -i -e "s|^$key.*$|$key\t$value|" $ZETC/libnss-mysql-root.cfg
        fi
done



for FILE in $FILES; do
	if [ -L "$ETC/$FILE" ]; then
		if [ $(stat -c %N $ETC/$FILE|awk '{print substr($3,2,length($3)-2)}') != '$ZETC/$FILE' ]; then
			rm -f $ETC/$FILE
			ln -s $ZETC/$FILE $ETC/$FILE
		fi
	else
		mv /etc/$FILE /etc/$FILE.orig
		ln -s $ZETC/$FILE $ETC/$FILE
	fi
done
